plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/zoumin/A1_4G/what-to-eat"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]